repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: [--line-length=88, --skip-string-normalization]
      python_version: python3.6
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v1.3.0
    hooks:
    -   id: flake8
        args: [--max-line-length=88]
    -   id: end-of-file-fixer
        files: \.(py|js)$
-   repo: git://github.com/doublify/pre-commit-isort
    rev: v4.3.0
    hooks:
    -   id: isort
