# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
version: 2
jobs:
  totem:
    docker:
    - image: python:alpine
      environment:
    steps:
    - checkout
    - add_ssh_keys:
        fingerprint:
          # a public Deploy key of the current repository
          "8e:61:1b:5d:a2:03:e7:56:3f:a5:f0:37:c8:d8:cc:c5"
    - run:
        name: Install git/openssh-client and add github to the list of known hosts
        command: apk add git openssh-client && mkdir ~/.ssh && ssh-keyscan github.com > ~/.ssh/known_hosts
    - run:
        name: Install totem
        command: pip install git+ssh://git@github.com/transifex/totem.git@devel
    - run:
        name: Run totem
        command: totem --pr-url "$CIRCLE_PULL_REQUEST" --config-file ".totem.yml" --details-url "$CIRCLE_BUILD_URL"

  build:
    working-directory: ~/transifex/totem
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/development.txt" }}
      - run:
          name: Install dependencies
          command: |
            python3 -m venv txenv
            . txenv/bin/activate
            pip install -r requirements/development.txt
      - save_cache:
          paths:
            - ./txenv
          key: deps1-{{ .Branch }}-{{ checksum "requirements/development.txt" }}

      - run:
          name: Run mypy
          command: |
            . txenv/bin/activate
            pip install mypy
            mypy totem --strict-optional

      - run:
          name: Run tests
          command: |
            . txenv/bin/activate
            coverage run --source totem --omit '*tests*' -m pytest
            coverage report -m
            coverage xml
            mkdir -p /tmp/test-results
            cp coverage.xml /tmp/test-results/test-results.xml
      - run:
          name: Upload coverage report
          command: |
            . txenv/bin/activate
            sudo pip install codecov
            codecov --token=9dcb14da-1951-4ff1-a39a-16381af243bc

workflows:
  version: 2
  run_tests:
    jobs:
      - build
  totem:
    jobs:
      - totem
